### ISSUE TITLE
Grafana + Prometheus 모니터링 구성

### ISSUE THREAD

**Issue by Hello-LSY** [LuckySevenLeeThree/l-place-back-end#4]
docker-compuse에 prometheus, grafana 추가

```yml
services:
  ...
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
```

prometheus.yml 추가

```yml
scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  # Redis Exporter 메트릭
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
          - 'redis-exporter:9121'

  # Spring Boot 애플리케이션
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'

```

![image](https://github.com/user-attachments/assets/7f492846-14af-4225-a9d0-1840af4dcd36)

prometheus 로그인데 이걸로 보기 힘드니까 grafana로 시각화

![image](https://github.com/user-attachments/assets/f683720e-b824-49fe-b927-ace8ebd921f6)
함수 커스텀해서 패널 만든 후 모니터링 띄울 수 있음
